### ISSUE TITLE
Review NER code changes made by Yvonne

### ISSUE THREAD

**Issue by Yvonne-Han** [iangow/se_features#19]
@iangow I've been playing with your NER tagging code these days and trying to get it running so that Maliha can use the output data for her thesis. 
As you can see from the [commit history](https://github.com/iangow/se_features/commits/master), I made some changes to your code but I am not 100% sure (some of your code I guess is project-specific for your non-answer paper?). So here's a summary of what I've changed and boxes for you to tick (important things in **bold**):

- [x] [#1](https://github.com/iangow/se_features/commit/c50051be30937e66fdc8b79408b2aad87ce580f7). `findner.py`: Checked and update the stanford_path to the latest one. This should be okay, and I assume I don't need to upload the Stanford NER files to GitHub? 
- [x] [#2](https://github.com/iangow/se_features/commit/27781e1353a898fbfc0aa8da7895459718baf834). `create_table.py`: Changed the target schema from `bs_linguistics` to `se_features` and changed the comment when creating table accordingly. This seems to be okay too. 
- [x] [#3](https://github.com/iangow/se_features/commit/68626b93816dd325fe68b40eac8ed5fa0e5746e1). `run_NER.py`: Changed the function `getFileNames` so that it gets files from `streetevents.calls` (later changed to `streetevents.speaker_data`) instead of `streetevents.qa_pairs`. I am not too sure about this step (as I don't know what your original code is dealing with) - **should I replace it with `speaker_data`?**
- [x] [#4](https://github.com/iangow/se_features/commit/f51cab7cc0e7ac760e885931cff6bc06122dbe60). `create_table.py`: Fixed a small typo in your SQL query when doing string replacements. I am quite confident about this.
- [x] [#5](https://github.com/iangow/se_features/commit/98739e232c420a2ce9ade963e6c7a595d51191f8). `findner.py`: Changed python2 to python3. Commented out your Anastasia & Ian Gow test cases. Shouldn't be a big deal.
- [x] [#6](https://github.com/iangow/se_features/commit/69ec296ebf4137eea00a541f78afd698559d43ef). `processFileNER.py`: Added some print functions for me to understand what is going on. Can be reverted later.
- [x] [#7](https://github.com/iangow/se_features/commit/bf6615395e00a7cc6be8c577cdcfb2a878739fed). & [#8](https://github.com/iangow/se_features/commit/13977e8b9b05d0641a584114b78cf88074edfa4d). `run_NER.py` & `processFileNER.py`: Fixed code for converting timestamp. The original code might be outdated. **This should be okay as long as I am converting things in the right way.** 
- [x] [#9](https://github.com/iangow/se_features/commit/bc443ed0f61b628c7394623a28544342886a22b6). `processFileNER.py`: I deleted an SQL query from your code: 
```
engine.execute("DELETE FROM %s.%s WHERE file_name ='%s'" % (ner_schema, ner_table, file_name))
```

**I don't really understand what is going on here so it is likely that I am making a mistake here.** If I include the SQL in the code, it seems to be producing a lot of `NA` entries and the number of `NA` increases as the code runs longer. So I decided to comment it out and it seems to work better (not sure). I've added a comment [here](https://github.com/iangow/se_features/commit/13977e8b9b05d0641a584114b78cf88074edfa4d) too so you can cross-reference it.
